### ISSUE TITLE
Страница входа - соглашение

### ISSUE THREAD

**Issue by Lipnevich** [Lipnevich/noxbox#8]
Приложение должно показывать флажок и ссылки на правила пользования и политики доверия.
Текст: 
Я прочел и согласен с Правилами Пользования и Политикой Конфиденциальности NoxBox.
I have read and agree to the NoxBox Terms of Use and Privacy Policy.

Кнопки входа должны становится активными только с отмеченным флажком.

Дизайн:
<img width="540" alt="login" src="https://user-images.githubusercontent.com/24192148/41114863-56f7dc88-6a8e-11e8-8267-e96c4ddc4023.png">

Готовность:
Флажок работает, текст на русском и английском, ссылки открываются в браузере

**Comment by Lipnevich** [comment]
Оценка первого задания 4 дня

**Comment by Lipnevich** [comment]
сделать схему страницы AuthPage скролируемой (кнопки недоступны если повернуть экран)

**Comment by Lipnevich** [comment]
изменить размеры текста, расположение значка кнопок по материал дизайну (https://material.io/design/components/buttons.html#specs)
Текст больше, отступ перед картинкой меньше
стоит ли нам перейти на MaterialButton?

**Comment by Lipnevich** [comment]
вынести текст соглашения в строки с переводом
Я прочел и согласен с Правилами пользования и Политикой конфиденциальности
I have read and agree with the Terms of Service and Privacy Policy

**Comment by Lipnevich** [comment]
сделать цвет колеса прогресса @color/primary

**Comment by Lipnevich** [comment]
убирать в сервисе надпись об отсутствии интернета по изменению состояния

**Comment by VladislawKravchenok** [comment]
Текст строки соглашения вынесен в строки.

Приёмник состояния сети добавлен, при её отсутствии появляется фрагмент уведомляющий что подключения нет, при включении интернета фрагмент удаляется.
